const request = require('supertest');

jest.mock('../services/auth.service', () => ({
  authenticateToken: jest.fn()
}));

jest.mock('../services/lecturerResearchTrends.service', () => ({
  getResearchTrends: jest.fn()
}));

const authService = require('../services/auth.service');
const lecturerResearchTrendsService = require('../services/lecturerResearchTrends.service');
const app = require('../server');

const lecturerUser = {
  id: 8,
  name: 'Lecturer Demo',
  email: 'lecturer.demo@uniosun.edu.ng',
  role: 'lecturer',
  status: 'active'
};

const studentUser = {
  id: 7,
  name: 'Student Demo',
  email: 'student.demo@uniosun.edu.ng',
  role: 'student',
  status: 'active'
};

const trendsSummary = {
  data: {
    topics: {
      total: 45,
      byLifecycle: {
        historical: 30,
        currentSession: 10,
        underReview: 5
      },
      byCategory: [
        { category: 'Public Health', count: 14 }
      ],
      bySessionYear: [
        { sessionYear: '2024/2025', count: 12 }
      ]
    },
    submissions: {
      total: 8,
      byStatus: {
        pendingReview: 2,
        awaitingRevision: 1,
        approved: 4,
        rejected: 1
      },
      decisionCoverage: {
        decided: 6,
        pending: 2
      },
      byCategory: [
        { category: 'Public Health', count: 3 }
      ]
    },
    similarityChecks: {
      snapshots: 7,
      byRisk: {
        high: 1,
        medium: 2,
        low: 3,
        unknown: 1
      },
      byResponseStatus: {
        success: 5,
        partialSuccess: 2,
        error: 0,
        other: 0
      },
      notes: ['Similarity trend counts use stored lecturer snapshots only.']
    },
    keywordTrends: {
      status: 'deferred',
      message: 'Keyword trend extraction and clustering are not generated by this endpoint.'
    },
    recommendations: {
      status: 'deferred',
      message: 'Research recommendations are deferred.'
    },
    warnings: []
  },
  meta: {
    generatedAt: '2026-06-07T16:00:00.000Z',
    dataCoverage: 'Read-only lecturer research trend aggregates from existing topic, submission, and similarity snapshot tables.',
    sourceTables: ['HistoricalTopic', 'Submission', 'SimilarityCheckSnapshot'],
    analyticsStatus: 'read_only_aggregates'
  }
};

describe('Lecturer research trends API routes', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('lecturer can read safe research trend aggregates', async () => {
    authService.authenticateToken.mockResolvedValue(lecturerUser);
    lecturerResearchTrendsService.getResearchTrends.mockResolvedValue(trendsSummary);

    const response = await request(app)
      .get('/api/v1/lecturer/research-trends')
      .set('Cookie', ['rtadss_session=signed-lecturer-token'])
      .expect(200);

    expect(response.body).toEqual({
      success: true,
      data: trendsSummary.data,
      meta: trendsSummary.meta
    });
    expect(lecturerResearchTrendsService.getResearchTrends).toHaveBeenCalledTimes(1);
    expect(response.body.data).not.toHaveProperty('downloadUrl');
    expect(response.body.data).not.toHaveProperty('recommendationItems');
    expect(response.body.data).not.toHaveProperty('actions');
  });

  test('unauthenticated users cannot read research trends', async () => {
    authService.authenticateToken.mockRejectedValue({
      statusCode: 401,
      code: 'AUTHENTICATION_REQUIRED',
      message: 'Authentication required.'
    });

    const response = await request(app)
      .get('/api/v1/lecturer/research-trends')
      .expect(401);

    expect(response.body).toMatchObject({
      status: 'error',
      details: {
        error_code: 'AUTHENTICATION_REQUIRED'
      }
    });
    expect(lecturerResearchTrendsService.getResearchTrends).not.toHaveBeenCalled();
  });

  test('non-lecturer users cannot read research trends', async () => {
    authService.authenticateToken.mockResolvedValue(studentUser);

    const response = await request(app)
      .get('/api/v1/lecturer/research-trends')
      .set('Cookie', ['rtadss_session=signed-student-token'])
      .expect(403);

    expect(response.body).toMatchObject({
      status: 'error',
      details: {
        error_code: 'FORBIDDEN'
      }
    });
    expect(lecturerResearchTrendsService.getResearchTrends).not.toHaveBeenCalled();
  });

  test('research trends response keeps keyword extraction and recommendations deferred', async () => {
    authService.authenticateToken.mockResolvedValue(lecturerUser);
    lecturerResearchTrendsService.getResearchTrends.mockResolvedValue(trendsSummary);

    const response = await request(app)
      .get('/api/v1/lecturer/research-trends')
      .set('Cookie', ['rtadss_session=signed-lecturer-token'])
      .expect(200);

    expect(response.body.data.keywordTrends).toEqual(expect.objectContaining({
      status: 'deferred'
    }));
    expect(response.body.data.recommendations).toEqual(expect.objectContaining({
      status: 'deferred'
    }));
    expect(response.body.data).not.toHaveProperty('fakeKeywords');
    expect(response.body.data).not.toHaveProperty('generatedInsights');
  });
});
