import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import ResearchTrendsPage from '../src/pages/lecturer/ResearchTrendsPage';
import apiClient from '../src/api/client';
import axios from 'axios';
import { getLecturerResearchTrends } from '../src/api/submissions';

vi.mock('axios', () => ({
  default: {
    get: vi.fn(),
    post: vi.fn(),
    patch: vi.fn(),
    delete: vi.fn()
  }
}));

vi.mock('../src/api/client', () => ({
  default: {
    get: vi.fn(),
    post: vi.fn(),
    patch: vi.fn(),
    delete: vi.fn()
  }
}));

vi.mock('../src/api/submissions', () => ({
  getLecturerResearchTrends: vi.fn()
}));

vi.mock('../src/auth/AuthContext', () => ({
  useAuth: () => ({
    user: {
      id: 8,
      email: 'lecturer.demo@uniosun.edu.ng',
      name: 'Lecturer Demo',
      role: 'lecturer'
    }
  })
}));

const trendsResponse = {
  data: {
    topics: {
      total: 45,
      byLifecycle: {
        historical: 30,
        currentSession: 10,
        underReview: 5
      },
      byCategory: [
        { category: 'Public Health', count: 14 },
        { category: 'Software Engineering', count: 6 }
      ],
      bySessionYear: [
        { sessionYear: '2024/2025', count: 12 },
        { sessionYear: '2025/2026', count: 11 }
      ]
    },
    submissions: {
      total: 8,
      byStatus: {
        pendingReview: 2,
        awaitingRevision: 1,
        approved: 4,
        rejected: 1
      },
      decisionCoverage: {
        decided: 6,
        pending: 2
      },
      byCategory: [
        { category: 'Public Health', count: 3 }
      ]
    },
    similarityChecks: {
      snapshots: 7,
      byRisk: {
        high: 1,
        medium: 2,
        low: 3,
        unknown: 1
      },
      byResponseStatus: {
        success: 5,
        partialSuccess: 2,
        error: 0,
        other: 0
      },
      notes: ['Similarity trend counts use stored lecturer snapshots only.']
    },
    keywordTrends: {
      status: 'deferred',
      message: 'Keyword trend extraction and clustering are not generated by this endpoint. No fake keywords or recommendations are returned.'
    },
    recommendations: {
      status: 'deferred',
      message: 'Research recommendations are deferred. This endpoint returns aggregate counts only.'
    },
    warnings: []
  },
  meta: {
    generatedAt: '2026-06-07T16:00:00.000Z',
    dataCoverage: 'Read-only lecturer research trend aggregates from existing topic, submission, and similarity snapshot tables.',
    sourceTables: ['HistoricalTopic', 'Submission', 'SimilarityCheckSnapshot'],
    analyticsStatus: 'read_only_aggregates'
  }
};

function renderPage() {
  return render(
    <MemoryRouter initialEntries={['/lecturer/research-trends']}>
      <ResearchTrendsPage />
    </MemoryRouter>
  );
}

function zeroTrendsResponse() {
  return {
    data: {
      topics: {
        total: 0,
        byLifecycle: { historical: 0, currentSession: 0, underReview: 0 },
        byCategory: [],
        bySessionYear: []
      },
      submissions: {
        total: 0,
        byStatus: { pendingReview: 0, awaitingRevision: 0, approved: 0, rejected: 0 },
        decisionCoverage: { decided: 0, pending: 0 },
        byCategory: []
      },
      similarityChecks: {
        snapshots: 0,
        byRisk: { high: 0, medium: 0, low: 0, unknown: 0 },
        byResponseStatus: { success: 0, partialSuccess: 0, error: 0, other: 0 },
        notes: []
      },
      keywordTrends: trendsResponse.data.keywordTrends,
      recommendations: trendsResponse.data.recommendations,
      warnings: []
    },
    meta: trendsResponse.meta
  };
}

describe('Lecturer ResearchTrendsPage', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.stubGlobal('fetch', vi.fn());
    getLecturerResearchTrends.mockResolvedValue(trendsResponse);
  });

  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it('renders real aggregate trends from the lecturer endpoint', async () => {
    renderPage();

    expect(screen.getByRole('heading', { name: /research trends/i })).toBeInTheDocument();
    expect(screen.getByText(/Loading research trends/i)).toBeInTheDocument();

    await waitFor(() => {
      expect(getLecturerResearchTrends).toHaveBeenCalledTimes(1);
    });

    expect(screen.getByText(/Real aggregate data/i)).toBeInTheDocument();
    expect(screen.getByText(/Topic records/i)).toBeInTheDocument();
    expect(screen.getByText('45')).toBeInTheDocument();
    expect(screen.getAllByText(/Public Health/i).length).toBeGreaterThanOrEqual(1);
    expect(screen.getByText(/2024\/2025/i)).toBeInTheDocument();
    expect(screen.getByText(/High risk/i)).toBeInTheDocument();
    expect(screen.getByText(/Partial success/i)).toBeInTheDocument();
  });

  it('keeps keyword trends and recommendations explicitly deferred', async () => {
    renderPage();

    await waitFor(() => {
      expect(getLecturerResearchTrends).toHaveBeenCalledTimes(1);
    });

    expect(screen.getByText(/Keyword trends deferred/i)).toBeInTheDocument();
    expect(screen.getByText(/Keyword trend extraction and clustering are not generated/i)).toBeInTheDocument();
    expect(screen.getByText(/Recommendations deferred/i)).toBeInTheDocument();
    expect(screen.getByText(/Research recommendations are deferred/i)).toBeInTheDocument();
  });

  it('shows an honest zero-data state without placeholder charts or insights', async () => {
    getLecturerResearchTrends.mockResolvedValue(zeroTrendsResponse());

    renderPage();

    await waitFor(() => {
      expect(screen.getByText(/Not enough trend data yet/i)).toBeInTheDocument();
    });

    expect(screen.getByText(/No placeholder charts, fake keywords, fake recommendations, or invented research insights are displayed/i)).toBeInTheDocument();
  });

  it('shows unavailable state without fallback trend data', async () => {
    getLecturerResearchTrends.mockRejectedValue(new Error('trends unavailable'));

    renderPage();

    await waitFor(() => {
      expect(screen.getByText(/Research trends unavailable/i)).toBeInTheDocument();
    });

    expect(screen.getByText(/No fallback charts, insights, or recommendations are displayed/i)).toBeInTheDocument();
  });

  it('does not expose mutations, exports, generated charts, or fake recommendation actions', async () => {
    renderPage();

    await waitFor(() => {
      expect(getLecturerResearchTrends).toHaveBeenCalledTimes(1);
    });

    expect(screen.queryByRole('button', { name: /export/i })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /download/i })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /generate/i })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /save/i })).not.toBeInTheDocument();
    expect(screen.queryByText(/recommended research area:/i)).not.toBeInTheDocument();
    expect(screen.queryByText(/fake insight/i)).not.toBeInTheDocument();
    expect(fetch).not.toHaveBeenCalled();
    expect(apiClient.post).not.toHaveBeenCalled();
    expect(apiClient.patch).not.toHaveBeenCalled();
    expect(apiClient.delete).not.toHaveBeenCalled();
    expect(axios.post).not.toHaveBeenCalled();
    expect(axios.patch).not.toHaveBeenCalled();
    expect(axios.delete).not.toHaveBeenCalled();
  });
});
